using System.Diagnostics;
using System.Net;
using System.Net.Sockets;
using System.Security.AccessControl;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Text;

namespace AmuleModern.Amule;

// Initial development host: owns exactly the process it starts, never attaches to an unknown one.
public sealed class EngineSession : IAsyncDisposable
{
    private Process? process;
    private FileStream? lease;
    public EcClient Client { get; private set; } = new();
    public string ProfilePath { get; private set; } = "";
    public int Port { get; private set; }
    public int? ProcessId => process is { HasExited: false } ? process.Id : null;
    public static string FindRepository()
    {
        for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir != null; dir = dir.Parent)
            if (File.Exists(Path.Combine(dir.FullName, "docs", "engine-manifest.json"))) return dir.FullName;
        throw new DirectoryNotFoundException("Ejecuta esta versión desde el repositorio amule-modern.");
    }
    public async Task StartAsync(string repository, string profileName, CancellationToken token = default)
    {
        if (process != null) throw new InvalidOperationException("La sesión ya tiene un proceso.");
        if (profileName.Any(c => !char.IsAsciiLetterOrDigit(c) && c != '-')) throw new ArgumentException("Perfil inválido.");
        ProfilePath = Path.Combine(repository, ".local", profileName);
        Directory.CreateDirectory(ProfilePath);
        if (OperatingSystem.IsWindows())
        {
            var acl = new DirectorySecurity();
            acl.SetAccessRuleProtection(true, false);
            var sid = WindowsIdentity.GetCurrent().User ?? throw new InvalidOperationException("Usuario Windows no disponible.");
            acl.SetOwner(sid);
            acl.AddAccessRule(new FileSystemAccessRule(sid, FileSystemRights.FullControl, InheritanceFlags.ContainerInherit | InheritanceFlags.ObjectInherit, PropagationFlags.None, AccessControlType.Allow));
            new DirectoryInfo(ProfilePath).SetAccessControl(acl);
        }
        lease = new FileStream(Path.Combine(ProfilePath, "frontend.lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
        string config = Path.Combine(ProfilePath, "amule.conf");
        string hash;
        if (!File.Exists(config))
        {
            Port = FreePort();
            hash = EcClient.Md5Hex(Convert.ToHexString(RandomNumberGenerator.GetBytes(32)));
            string incoming = Path.Combine(ProfilePath, "Incoming"), temp = Path.Combine(ProfilePath, "Temp");
            Directory.CreateDirectory(incoming); Directory.CreateDirectory(temp);
            // Minimal isolated profile, normalized below before launching the motor.
            string text = $"[eMule]\nNick=AmuleModern\nAppVersion=3.0.1\nIncomingDir={incoming}\nTempDir={temp}\nPort={FreePort()}\nUDPPort={FreePort()}\nAutoconnect=0\nReconnect=0\nConnectToKad=0\nConnectToED2K=0\nUPnPEnabled=0\n[ExternalConnect]\nAcceptExternalConnections=1\nECAddress=127.0.0.1\nECPort={Port}\nECPassword={hash}\n[WebServer]\nEnabled=0\n";
            File.WriteAllText(config, text, new UTF8Encoding(false));
        }
        else
        {
            // Configuration generated by this host. The profile is never an existing user installation.
            var lines = File.ReadAllLines(config);
            Port = int.Parse(lines.Single(l => l.StartsWith("ECPort=", StringComparison.Ordinal))[7..]);
            hash = lines.Single(l => l.StartsWith("ECPassword=", StringComparison.Ordinal))[11..];
        }
        // aMule only initializes/persists server.met when eD2k is enabled at startup.
        // Its daemon otherwise bootstraps an empty list from the Internet and connects
        // even with Autoconnect=0. Clear that bootstrap URL in our managed profile.
        // wxFileConfig interprets backslashes as escapes: use forward slashes for paths.
        string original = File.ReadAllText(config);
        var settings = new Dictionary<string, string>
        {
            ["ConnectToED2K"] = "1", ["Autoconnect"] = "0", ["Reconnect"] = "0",
            ["Ed2kServersUrl"] = "", ["Serverlist"] = "0", ["NewVersionCheck"] = "0",
            ["IncomingDir"] = Path.Combine(ProfilePath, "Incoming").Replace('\\', '/'),
            ["TempDir"] = Path.Combine(ProfilePath, "Temp").Replace('\\', '/')
        };
        var configLines = original.Replace("\r\n", "\n").Split('\n').ToList();
        int section = configLines.IndexOf("[eMule]");
        int end = configLines.FindIndex(section + 1, line => line.StartsWith('['));
        if (end < 0) end = configLines.Count;
        foreach (var setting in settings)
        {
            int index = configLines.FindIndex(section + 1, end - section - 1, line => line.StartsWith(setting.Key + "=", StringComparison.Ordinal));
            if (index >= 0) configLines[index] = setting.Key + "=" + setting.Value;
            else { configLines.Insert(end++, setting.Key + "=" + setting.Value); }
        }
        string updated = string.Join("\n", configLines);
        if (original != updated)
        {
            if (!File.Exists(config + ".pre-servers.bak")) File.Copy(config, config + ".pre-servers.bak");
            File.WriteAllText(config, updated, new UTF8Encoding(false));
        }
        var probe = new TcpListener(IPAddress.Loopback, Port);
        probe.Start(); probe.Stop(); // Refuse occupied ports before launching.
        string engine = Path.Combine(repository, "vendor", "amule-3.0.1", "amule-portable-x64", "bin", "amuled.exe");
        if (!File.Exists(engine)) throw new FileNotFoundException("Ejecuta scripts/Setup.ps1 para obtener el motor.");
        var start = new ProcessStartInfo(engine) { UseShellExecute = false, CreateNoWindow = true, WorkingDirectory = Path.GetDirectoryName(engine)!, RedirectStandardOutput = true, RedirectStandardError = true };
        start.ArgumentList.Add("-c"); start.ArgumentList.Add(ProfilePath);
        start.ArgumentList.Add("-o");
        process = Process.Start(start) ?? throw new IOException("No se pudo iniciar amuled.");
        // Drain both pipes to prevent blocking. Engine keeps its own logfile in the private profile.
        process.OutputDataReceived += (_, _) => { }; process.ErrorDataReceived += (_, _) => { };
        process.BeginOutputReadLine(); process.BeginErrorReadLine();
        for (int attempt = 0; attempt < 50; attempt++)
        {
            token.ThrowIfCancellationRequested();
            if (process.HasExited) throw new IOException($"amuled terminó ({process.ExitCode}). Revisa el logfile del perfil.");
            Client.Dispose(); Client = new EcClient();
            try { await Client.ConnectAsync(Port, hash, token); return; }
            catch (SocketException) { await Task.Delay(200, token); }
        }
        throw new TimeoutException("amuled no abrió la conexión EC a tiempo.");
    }
    private static int FreePort()
    {
        var listener = new TcpListener(IPAddress.Loopback, 0);
        listener.Start(); int port = ((IPEndPoint)listener.LocalEndpoint).Port; listener.Stop(); return port;
    }
    public async Task StopAsync()
    {
        if (process is { HasExited: false })
        {
            // Reauthenticate on a fresh connection if earlier I/O invalidated the stream.
            Client.Dispose(); Client = new EcClient();
            string hash = File.ReadAllLines(Path.Combine(ProfilePath, "amule.conf")).Single(l => l.StartsWith("ECPassword=", StringComparison.Ordinal))[11..];
            await Client.ConnectAsync(Port, hash);
            await Client.RequestAsync(new(8));
            using var deadline = new CancellationTokenSource(TimeSpan.FromSeconds(15));
            await process.WaitForExitAsync(deadline.Token);
        }
        Client.Dispose(); process?.Dispose(); process = null;
        lease?.Dispose(); lease = null;
    }
    public async ValueTask DisposeAsync() => await StopAsync();
}
